---
title: "Differential Expression"
author: "Sofia Salazar"
date: "2022-11-14"
output: html_document
---

## Setup

```{bash}
qlogin
cd /mnt/Citosina/amedina/ssalazar/meta/RNA2/out
module load r/4.0.2
R
```

## Libraries

```{r}
library(edgeR)
library(tidyverse)
library(limma)
```

## Loading data

```{r}
summary <- read_csv("/mnt/Citosina/amedina/ssalazar/meta/RNA2/summary.csv")
setwd("/mnt/Citosina/amedina/ssalazar/meta/RNA2/out/")
dge_files<- dir(pattern="dge-")
design_files<-dir(pattern="design-")
names <- summary$SRA
curation <-  readRDS("/mnt/Citosina/amedina/ssalazar/meta/RNA2/curated_rse.xz")
```


## Differential expression


```{r}
for (i in 1:length(dge_files)){
  dge_result <- readRDS(dge_files[i])
  design <- readRDS(design_files[i])
  rse_object <- curation[[i]]
  study <- names[i]
  vGene <- voom(dge_result, design, plot = F)
  eb_results <- eBayes(lmFit(vGene))
  de_results <- topTable(eb_results, coef = ncol(design), number = nrow(rse_object), sort.by = "none", confint = T)
  res <- as_tibble(de_results,rownames="rownames")
  colnames(res) <- str_c(colnames(res), "_", study)
  write_csv(as.data.frame(res), file = str_c("/mnt/Citosina/amedina/ssalazar/meta/RNA2/out/DE/Table_Genes_", study, ".csv"))
}
```

## Session Info

```{r}
sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS:   /cm/shared/apps/r/4.0.2-studio/lib64/R/lib/libRblas.so
LAPACK: /cm/shared/apps/r/4.0.2-studio/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
 [1] SummarizedExperiment_1.20.0 Biobase_2.50.0             
 [3] GenomicRanges_1.42.0        GenomeInfoDb_1.26.7        
 [5] IRanges_2.24.1              S4Vectors_0.28.1           
 [7] BiocGenerics_0.36.1         MatrixGenerics_1.2.1       
 [9] matrixStats_0.60.0          forcats_0.5.1              
[11] stringr_1.4.0               dplyr_1.0.3                
[13] purrr_0.3.4                 readr_1.4.0                
[15] tidyr_1.1.2                 tibble_3.1.3               
[17] ggplot2_3.3.5               tidyverse_1.3.0            
[19] edgeR_3.32.1                limma_3.46.0               

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7             locfit_1.5-9.4         lubridate_1.7.9.2     
 [4] lattice_0.20-41        assertthat_0.2.1       utf8_1.2.2            
 [7] R6_2.5.0               cellranger_1.1.0       backports_1.2.1       
[10] reprex_1.0.0           httr_1.4.2             pillar_1.6.2          
[13] zlibbioc_1.36.0        rlang_0.4.11           readxl_1.3.1          
[16] rstudioapi_0.13        Matrix_1.3-4           RCurl_1.98-1.3        
[19] munsell_0.5.0          DelayedArray_0.16.3    broom_0.7.9           
[22] compiler_4.0.2         modelr_0.1.8           pkgconfig_2.0.3       
[25] tidyselect_1.1.0       GenomeInfoDbData_1.2.4 fansi_0.5.0           
[28] crayon_1.4.1           dbplyr_2.0.0           withr_2.4.2           
[31] bitops_1.0-7           grid_4.0.2             jsonlite_1.7.2        
[34] gtable_0.3.0           lifecycle_1.0.0        DBI_1.1.1             
[37] magrittr_2.0.1         scales_1.1.1           cli_3.0.1             
[40] stringi_1.6.2          XVector_0.30.0         fs_1.5.0              
[43] xml2_1.3.2             ellipsis_0.3.2         generics_0.1.0        
[46] vctrs_0.3.8            tools_4.0.2            glue_1.4.2            
[49] hms_1.1.0              colorspace_2.0-2       rvest_0.3.6           
[52] haven_2.3.1 
```


