---
title: "Merging"
author: "Sofia Salazar"
date: "2022-11-23"
output: html_document
---

```{bash}
qlogin
cd /mnt/Citosina/amedina/ssalazar/meta/RNA2/out
module load r/4.0.2
R
```

## Libraries

```{r}
library(tidyverse)
```

### Import data

We will import DE results from all experiments. 

```{r}
files <- list.files("/mnt/Citosina/amedina/ssalazar/meta/RNA2/out/DE", full.names = T)
files <- gtools::mixedsort(files)[-10]
data <- files %>% map(read_csv)
```

## Merge data

```{r}
class(data[[1]]$rownames)
column_selection <- function(df){
  geneID <- str_subset(colnames(df),"rownames")
  logFC <- str_subset(colnames(df),"logFC|log2FoldChange")
  adjP <- str_subset(colnames(df),"adj.P.Val")
  CI.L <- str_subset(colnames(df),"CI.L")
  CI.R <- str_subset(colnames(df),"CI.R")
  lfcSE <- str_subset(colnames(df),"lfcSE")
  
  selectedColumns <- c(geneID,logFC,adjP,CI.L,CI.R,lfcSE)
  #Return subset of dataframe to only keep the first duplicate
  DF <- df[!duplicated(df[,geneID]),selectedColumns] %>%
    rename(ID = geneID)
  
  return(DF)
}

name_short<-function(table){
  table$ID <- gsub("\\..*","", table$ID)
  return(table)
}
```

Joining all data into a single dataset

```{r merge}
full_tables <- data %>% 
  map(column_selection)%>% 
  lapply(name_short)%>% 
  # joining using the same gene ID
  purrr::reduce(full_join, by = "ID") 
full_tables ## Select genes with at least 2 experiments with data information
genes <- full_tables %>% 
  select(ID,str_subset(colnames(full_tables),"logFC")) %>%
  filter(rowSums(is.na(.)) < 9 ) %>% # at least 3 experiments with logFC (9/12 NA)
  select(ID)
full_tables <- filter(full_tables, ID %in% genes$ID)
full_tables <- full_tables[which(!is.na(full_tables$ID)),]
dim(full_tables)
length(unique(full_tables$ID))


write_csv(full_tables, file= "/mnt/Citosina/amedina/ssalazar/meta/RNA2/out/mergedTables.csv")
```

## Getting gene symbols

```{r}
library("biomaRt")
mart <- useMart(biomart="ensembl", dataset="hsapiens_gene_ensembl")
genes <- getBM(attributes = c("ensembl_gene_id", "hgnc_symbol","transcript_biotype"),
                          filters = c("ensembl_gene_id"), 
                          values = full_tables$ID,
                          mart = mart)
names(genes)[1] <- "ID"
names(genes)[2] <- "gene_name"

dim(genes)
length(unique(genes$gene_name))

protein_coding<-subset(genes, transcript_biotype =="protein_coding")
dim(protein_coding)
dim(protein_coding[unique(protein_coding$gene_name),]) # 14982
non.dup <- protein_coding[!duplicated(protein_coding$gene_name),]
dim(non.dup) # 14982

full_tables <- list(full_tables, non.dup) %>% purrr::reduce(full_join, by = "ID")

write_csv(full_tables, file= "/mnt/Citosina/amedina/ssalazar/meta/RNA2/out/mergedTables_symbol.csv")
tab <- full_tables[!is.na(full_tables$transcript_biotype),]
dim(tab)# 14982
length(unique(tab$gene_name))# 14982
```

## Output

```{r}
write_csv(tab, file= "/mnt/Citosina/amedina/ssalazar/meta/RNA2/out/merged_protein_coding.csv")
```

## Session Info

```{r}
sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS:   /cm/shared/apps/r/4.0.2-studio/lib64/R/lib/libRblas.so
LAPACK: /cm/shared/apps/r/4.0.2-studio/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] biomaRt_2.46.2  forcats_0.5.1   stringr_1.4.0   dplyr_1.0.3    
 [5] purrr_0.3.4     readr_1.4.0     tidyr_1.1.2     tibble_3.1.3   
 [9] ggplot2_3.3.5   tidyverse_1.3.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7           lubridate_1.7.9.2    prettyunits_1.1.1   
 [4] gtools_3.8.2         assertthat_0.2.1     utf8_1.2.2          
 [7] BiocFileCache_1.14.0 R6_2.5.0             cellranger_1.1.0    
[10] backports_1.2.1      reprex_1.0.0         stats4_4.0.2        
[13] RSQLite_2.2.7        httr_1.4.2           pillar_1.6.2        
[16] rlang_0.4.11         progress_1.2.2       curl_4.3.2          
[19] readxl_1.3.1         rstudioapi_0.13      blob_1.2.1          
[22] S4Vectors_0.28.1     bit_4.0.4            munsell_0.5.0       
[25] broom_0.7.9          compiler_4.0.2       modelr_0.1.8        
[28] askpass_1.1          pkgconfig_2.0.3      BiocGenerics_0.36.1 
[31] openssl_1.4.4        tidyselect_1.1.0     IRanges_2.24.1      
[34] XML_3.99-0.6         fansi_0.5.0          crayon_1.4.1        
[37] dbplyr_2.0.0         withr_2.4.2          rappdirs_0.3.3      
[40] grid_4.0.2           jsonlite_1.7.2       gtable_0.3.0        
[43] lifecycle_1.0.0      DBI_1.1.1            magrittr_2.0.1      
[46] scales_1.1.1         cli_3.0.1            stringi_1.6.2       
[49] cachem_1.0.5         fs_1.5.0             xml2_1.3.2          
[52] ellipsis_0.3.2       generics_0.1.0       vctrs_0.3.8         
[55] tools_4.0.2          bit64_4.0.5          Biobase_2.50.0      
[58] glue_1.4.2           hms_1.1.0            parallel_4.0.2      
[61] fastmap_1.1.0        AnnotationDbi_1.52.0 colorspace_2.0-2    
[64] rvest_0.3.6          memoise_2.0.0        haven_2.3.1
```

